---
rule-providers:
  G1直连:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/rolay/clash@main/G1.yaml
    path: "./rule_provider/GoogleOne"
    format: yaml
    interval: 86400
  proxy:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/rolay/clash@main/proxy.yaml
    path: "./rule_provider/Proxy"
    format: yaml
    interval: 86400
proxies:
proxy-groups:
rules:
redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: info
ipv6: false
tcp-concurrent: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
  - 223.5.5.5
  - 10.0.0.10
  - 114.114.114.114
  - 119.29.29.29
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  - https://dns.cloudflare.com/dns-query
  - https://public.dns.iij.jp/dns-query
  - https://jp.tiar.app/dns-query
  - https://jp.tiarap.org/dns-query
  - tls://dot.tiar.app
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
tun:
  enable: true
  stack: system
  device: utun
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
  - tcp://any:53
profile:
  store-selected: true
